# Generated by Django 5.0.7 on 2024-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
